apiVersion: v1
kind: Pod
metadata:
  name: disallowed-example-no-secrets-as-env-vars
  namespace: pizza
spec:
  containers:
  - name: test
    image: redis
    env:
    - name: MY_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: password

