apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: taco
  name: pod-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["*"]
  verbs: ["get", "watch", "list"]
